---
services:

  minerd:
    image: jahrik/arm-m-minerd:latest
    # xmg.minerclaim.net:3333
    # xmg.minerclaim.net:7008
    environment:
      M_USER: "${M_USER}"
      M_WORK: "${M_WORK}"
      M_PASS: "${M_PASS}"
      M_URL: "${M_URL:-stratum+tcp://xmg.minerclaim.net:3333}"
      M_CPU: "${M_CPU:-50}"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.miner == true]
