version: '3'

services:

  minerd:
    image: jahrik/arm-m-minerd
    # xmg.minerclaim.net:3333
    # xmg.minerclaim.net:7008
    environment:
      - M_USER: "${M_USER}"
      - M_WORK: "${M_PASS}"
      - M_PASS: "${M_PASS}"
      - M_URL: "${M_URL}"
      - M_CPU: "${M_CPU}"
    deploy:
      mode: global
      placement:
        constraints: [node.labels.miner == true ]
#       resources:
#         limits:
#           cpus: '4'
